use super::save_settings::Category;

impl Category {
    #[must_use]
    pub fn extensions(self) -> &'static [&'static str] {
        match self {
            Self::General => &[],
            Self::Compressed => &[
                "7z", "ace", "alz", "arc", "arj", "br", "bz", "bz2", "cab", "cpio", "crx", "deb",
                "ear", "gem", "gz", "gzip", "hqx", "jar", "lha", "lzh", "lz", "lz4", "lzma", "lzo",
                "nupkg", "pak", "pea", "rar", "rpm", "sea", "sit", "sitx", "tar", "taz", "tbz",
                "tbz2", "tgz", "tlz", "txz", "tz", "vsix", "war", "whl", "xar", "xpi", "xz", "z",
                "zip", "zipx", "zoo", "zst", "001",
            ],
            Self::Documents => &[
                "abw", "asc", "ascii", "chm", "csv", "doc", "docm", "docx", "dot", "dotm", "dotx",
                "eml", "emlx", "fodg", "fodp", "fods", "fodt", "hlp", "ics", "key", "latex", "log",
                "ltx", "md", "mdown", "mht", "mhtml", "mkd", "msg", "numbers", "odc", "odg", "odm",
                "odp", "ods", "odt", "one", "onepkg", "onetoc2", "otp", "ots", "ott", "oxps",
                "pages", "pdf", "pot", "potm", "potx", "pps", "ppsm", "ppsx", "ppt", "pptm",
                "pptx", "psv", "pub", "rst", "rtf", "tex", "text", "tsv", "txt", "vcf", "vcs",
                "vsd", "vsdx", "vss", "vst", "vsx", "wp", "wpd", "wps", "wpt", "xls", "xlsb",
                "xlsm", "xlsx", "xlt", "xltm", "xltx", "xps",
            ],
            Self::Music => &[
                "8svx", "aa", "aac", "aax", "ac3", "aif", "aifc", "aiff", "alac", "amr", "ape",
                "au", "awb", "caf", "dff", "dsd", "dsf", "dts", "dtshd", "eac3", "flac", "it",
                "kar", "m3u", "m3u8", "m4a", "m4b", "m4p", "mid", "midi", "mka", "mod", "mp2",
                "mp3", "mpa", "mpc", "mpp", "mtm", "oga", "ogg", "opus", "pls", "ra", "ram", "rmi",
                "s3m", "shn", "snd", "spx", "tak", "tta", "umx", "voc", "wav", "wave", "wma", "wv",
                "xm",
            ],
            Self::Programs => &[
                "aab",
                "air",
                "apk",
                "app",
                "appimage",
                "appinstaller",
                "appx",
                "appxbundle",
                "bat",
                "cmd",
                "com",
                "cpl",
                "dll",
                "drv",
                "dylib",
                "efi",
                "elf",
                "exe",
                "flatpak",
                "flatpakref",
                "gadget",
                "hta",
                "ipa",
                "mpkg",
                "msi",
                "msp",
                "msix",
                "msixbundle",
                "msu",
                "ocx",
                "pkg",
                "ps1",
                "psd1",
                "psm1",
                "run",
                "scr",
                "snap",
                "so",
                "sys",
                "vbe",
                "vbs",
                "wsf",
                "wsh",
                "xap",
                "xbe",
                "xex",
            ],
            Self::Video => &[
                "264", "265", "3g2", "3gp", "3gpp", "3gpp2", "amv", "asf", "asx", "av1", "avc",
                "avi", "bik", "divx", "dvr-ms", "f4p", "f4v", "flv", "hevc", "m1v", "m2p", "m2ts",
                "m2v", "m4v", "mjpeg", "mjpg", "mkv", "mov", "mp4", "mp4v", "mpe", "mpeg", "mpg",
                "mpv", "mpv4", "mqv", "mts", "mtv", "mxf", "ogm", "ogv", "ogx", "qt", "rm", "rmvb",
                "roq", "smk", "swf", "ts", "vob", "webm", "wm", "wmv", "wmx", "wtv", "wvx", "xvid",
                "y4m", "yuv",
            ],
            Self::Images => &[
                "3fr", "ai", "apng", "arw", "avif", "bmp", "cdr", "cgm", "clip", "cr2", "cr3",
                "crw", "csp", "cur", "dds", "dib", "dng", "emf", "erf", "exr", "flif", "gbr",
                "gif", "gih", "hdr", "heic", "heif", "icns", "ico", "j2k", "jfif", "jfi", "jpe",
                "jpeg", "jpg", "jp2", "jpf", "jpm", "jpx", "jxl", "kdc", "kra", "ktx", "mef",
                "mos", "mrw", "nef", "nrw", "ora", "orf", "pam", "pbm", "pcc", "pcx", "pdn", "pef",
                "pgm", "pic", "pnm", "ppm", "psb", "psd", "psp", "qoi", "raf", "ras", "raw", "rw2",
                "rwl", "sai", "sr2", "srw", "sun", "svg", "svgz", "tga", "tif", "tiff", "webp",
                "wmf", "x3f", "xbm", "xcf", "xpm",
            ],
            Self::Ebooks => &[
                "azw", "azw1", "azw3", "azw4", "cb7", "cba", "cbr", "cbt", "cbz", "djv", "djvu",
                "epub", "epub3", "fb2", "fb3", "ibooks", "imp", "kf8", "kfx", "lit", "lrf", "lrx",
                "mobi", "oeb", "pml", "prc", "snb", "tcr", "tpz", "tr2", "tr3",
            ],
            Self::SourceCode => &[
                "ada",
                "adb",
                "ads",
                "asm",
                "asp",
                "aspx",
                "avsc",
                "bash",
                "c",
                "cc",
                "clj",
                "cljc",
                "cljs",
                "cmake",
                "coffee",
                "cpp",
                "cs",
                "csh",
                "css",
                "cxx",
                "d",
                "dart",
                "ejs",
                "el",
                "elm",
                "erb",
                "erl",
                "ex",
                "exs",
                "f",
                "f03",
                "f77",
                "f90",
                "f95",
                "fish",
                "frag",
                "fs",
                "fsi",
                "fsx",
                "glsl",
                "go",
                "gql",
                "gradle",
                "graphql",
                "groovy",
                "gvy",
                "h",
                "haml",
                "hbs",
                "hh",
                "hlsl",
                "hpp",
                "hrl",
                "hs",
                "htm",
                "html",
                "hxx",
                "ini",
                "java",
                "jl",
                "jsp",
                "js",
                "json",
                "json5",
                "jsonc",
                "jsonl",
                "jsx",
                "kt",
                "kts",
                "less",
                "lhs",
                "liquid",
                "lisp",
                "ls",
                "lsp",
                "lua",
                "m",
                "mak",
                "mk",
                "mjs",
                "ml",
                "mli",
                "mm",
                "mustache",
                "ndjson",
                "nim",
                "pas",
                "php",
                "php3",
                "php4",
                "php5",
                "php7",
                "phtml",
                "pl",
                "plist",
                "pm",
                "pod",
                "pp",
                "properties",
                "proto",
                "pug",
                "py",
                "pyi",
                "pyw",
                "r",
                "rake",
                "rb",
                "rbx",
                "rkt",
                "rmd",
                "rs",
                "sass",
                "scala",
                "scm",
                "scss",
                "sh",
                "slim",
                "sol",
                "ss",
                "styl",
                "svelte",
                "sv",
                "svh",
                "swift",
                "t",
                "tf",
                "tfvars",
                "thrift",
                "toml",
                "tsx",
                "twig",
                "v",
                "vert",
                "vue",
                "wgsl",
                "xhtml",
                "xml",
                "xsd",
                "xsl",
                "xslt",
                "yaml",
                "yml",
                "zig",
            ],
            Self::DiskImages => &[
                "2mg",
                "adf",
                "bin",
                "ccd",
                "cdi",
                "cue",
                "d64",
                "dd",
                "dmg",
                "dsk",
                "esd",
                "gcm",
                "gho",
                "gi",
                "hdd",
                "hdf",
                "ima",
                "img",
                "imz",
                "ipsw",
                "iso",
                "mds",
                "nrg",
                "pvm",
                "qcow",
                "qcow2",
                "qed",
                "sparsebundle",
                "sparseimage",
                "swm",
                "tib",
                "toast",
                "vbox",
                "vdi",
                "vhd",
                "vhdx",
                "vmdk",
                "vvfat",
                "wim",
                "wud",
                "wux",
            ],
            Self::Torrents => &["magnet", "meta4", "metalink", "nzb", "torrent"],
            Self::Databases => &[
                "accdb", "accde", "accdr", "accdw", "db", "db3", "dbf", "dbt", "ddl", "dml", "dsn",
                "dump", "frm", "ibd", "ldf", "lmdb", "mdb", "mdbx", "mdf", "myi", "myd", "ndf",
                "realm", "sdf", "sql", "sqlite", "sqlite2", "sqlite3", "sqlitedb", "udl",
            ],
        }
    }
}
